# Shared helpers for the package-consumer scripts.

set(_step 0)
function(step_run description)
    cmake_parse_arguments(PARSE_ARGV 1 S "" "OUTPUT_VAR;EXPECT_FAILURE" "COMMAND")
    math(EXPR n "${_step} + 1")
    set(_step ${n} PARENT_SCOPE)
    message(STATUS "[package-consumer ${n}] ${description}")
    execute_process(COMMAND ${S_COMMAND}
        RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(S_OUTPUT_VAR)
        set(${S_OUTPUT_VAR} "${out}\n${err}" PARENT_SCOPE)
    endif()
    if(S_EXPECT_FAILURE)
        if(rc EQUAL 0)
            message(FATAL_ERROR "[package-consumer] expected failure but succeeded: ${description}")
        endif()
    elseif(NOT rc EQUAL 0)
        message(FATAL_ERROR "[package-consumer] FAILED: ${description}\n${out}\n${err}")
    endif()
endfunction()

function(expect_contains text needle what)
    string(FIND "${text}" "${needle}" pos)
    if(pos EQUAL -1)
        message(FATAL_ERROR "[package-consumer] ${what}: expected to find\n  ${needle}")
    endif()
endfunction()

function(expect_missing text needle what)
    string(FIND "${text}" "${needle}" pos)
    if(NOT pos EQUAL -1)
        message(FATAL_ERROR "[package-consumer] ${what}: must not contain\n  ${needle}")
    endif()
endfunction()
