# sega_bg - Sega Saturn wallpaper background
EXAMPLE_INPUT        := examples/$(EXAMPLE)/assets/sega_bg.png
EXAMPLE_RESIZE       := 320 224
EXAMPLE_ASSET_PREFIX := $(GENERATED_DIR)/sega_bg/bg
EXAMPLE_ASSETS       := $(EXAMPLE_ASSET_PREFIX).c
EXAMPLE_HEADERS      := $(EXAMPLE_ASSET_PREFIX).h
