#ifndef SATURN_ANIM3D_H
#define SATURN_ANIM3D_H

#include <stdint.h>

#include "saturn/core.h"
#include "saturn/math3d.h"
#include "saturn/mesh3d.h"
#include "saturn/model3d.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------ */
/* Baked vertex-animation assets (generated by tools/import_model.py)  */
/* ------------------------------------------------------------------ */
/* The source asset stays skeletal; the Saturn runtime never skins. The
 * host skinning evaluator bakes simplified-model vertex positions for
 * every runtime animation frame, and the generated asset carries that
 * compact pose stream plus the shared static indices/textures from
 * sat_model_asset_t. Texture mapping, face indices and material
 * assignment are shared across all frames: there is one texture set, one
 * index list, and N vertex frames.
 *
 * Positions quantize to signed 16-bit per axis around a per-model
 * scale/bias; the importer reports the measured quantization error and
 * refuses encodings that damage the model past the quality gate:
 *
 *   pos_fx16 = bias + (scale * q) / 32767,  q in [-32767, 32767]
 *
 * Storage is caller-owned like sat_mesh_t: the asset points at const
 * generated arrays, animation state lives in a caller struct, and pose
 * decoding writes into a caller vertex buffer. No heap, no globals. */

typedef struct sat_anim_position_encoding {
    sat_fx16_t bias_x;
    sat_fx16_t bias_y;
    sat_fx16_t bias_z;
    sat_fx16_t scale_x;
    sat_fx16_t scale_y;
    sat_fx16_t scale_z;
} sat_anim_position_encoding_t;

#define SAT_ANIM_FLAG_LOOP 0x0001u

typedef struct sat_model_animation_asset {
    /* frame_count * vertex_count * 3 int16, frame-major: frame f, vertex v,
     * axis a lives at positions[(f * vertex_count + v) * 3 + a]. */
    const int16_t* positions;
    uint16_t frame_count;
    uint16_t vertex_count;
    /* Clip rate in frames per second = sample_rate_num / sample_rate_den
     * (30/1 for a 30 Hz clip). The runtime advances with a fixed-point
     * time accumulator, so NTSC (~60 Hz VBlank) and PAL (~50 Hz) both land
     * on correct frames without an integer-divisor assumption. */
    uint16_t sample_rate_num;
    uint16_t sample_rate_den;
    uint16_t flags;
    uint16_t reserved;
    sat_anim_position_encoding_t encoding;
} sat_model_animation_asset_t;

typedef struct sat_animated_model_asset {
    const sat_model_asset_t* model;
    const sat_model_animation_asset_t* animations;
    uint16_t animation_count;
    uint16_t reserved;
} sat_animated_model_asset_t;

/* Caller-owned playback state. `time` is 16.16 seconds into the clip;
 * `frame` is the decoded frame index for `time` (updated by advance). */
#define SAT_ANIM_STATE_PAUSED 0x0001u

typedef struct sat_anim_state {
    uint16_t clip;
    uint16_t frame;
    uint16_t flags;
    uint16_t reserved;
    sat_fx16_t time;
} sat_anim_state_t;

/* Descriptor validation without touching hardware. Checks counts, nulls,
 * rate denominators, vertex-count agreement with the static model, and
 * encoding ranges. */
sat_result_t sat_anim_validate(const sat_animated_model_asset* asset);
sat_result_t sat_anim_clip_validate(const sat_animated_model_asset* asset, uint16_t clip);

/* Clip duration in 16.16 seconds (frame_count at the clip rate). */
sat_fx16_t sat_anim_clip_duration(const sat_animated_model_asset* asset, uint16_t clip);

/* Binds state to a clip at time zero. */
sat_result_t sat_anim_state_init(
    sat_anim_state_t* state,
    const sat_animated_model_asset* asset,
    uint16_t clip
);
sat_result_t sat_anim_set_clip(
    sat_anim_state_t* state,
    const sat_animated_model_asset* asset,
    uint16_t clip
);
sat_result_t sat_anim_reset(sat_anim_state_t* state);
void sat_anim_set_paused(sat_anim_state_t* state, int paused);
int sat_anim_is_paused(const sat_anim_state_t* state);

/* Advances `time` by dt (16.16 seconds, e.g. one VBlank interval) and
 * updates `frame`. Looping clips wrap; non-looping clips hold the final
 * frame. A paused state is left untouched and still returns SAT_OK. */
sat_result_t sat_anim_advance(
    sat_anim_state_t* state,
    const sat_animated_model_asset* asset,
    sat_fx16_t dt_fx16
);

/* Decodes the current frame into caller storage (`vertex_count` entries).
 * Touches no texture state. Returns SAT_ERR_CAPACITY when vertex_cap is
 * too small (writes nothing) and SAT_ERR_INVALID_ARG for a malformed
 * request. Feed the output to a sat_mesh_t's vertices before drawing. */
sat_result_t sat_anim_decode(
    const sat_animated_model_asset* asset,
    const sat_anim_state_t* state,
    sat_vec3_t* out_vertices,
    uint16_t vertex_cap
);

#ifdef __cplusplus
}
#endif

#endif /* SATURN_ANIM3D_H */
