#ifndef SATURN_MODEL3D_H
#define SATURN_MODEL3D_H

#include <stdint.h>

#include "saturn/core.h"
#include "saturn/math3d.h"
#include "saturn/mesh3d.h"
#include "saturn/vdp1.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------ */
/* Compiled model assets (generated by tools/import_model.py)          */
/* ------------------------------------------------------------------ */
/* A compiled model is immutable generated data: vertices already in
 * LibSaturn 16.16 fixed point, faces already in A/B/C/D ordering with the
 * outward normal at cross(D-A, B-A), and one baked VDP1-legal texture per
 * unique face appearance. No OBJ/MTL/PNG parsing happens on the Saturn.
 *
 * Source UVs are importer input, not runtime state: the generated asset
 * contains no source UV table, only the baked canonical textures and the
 * face->texture mapping the VDP1 distorted-sprite path consumes.
 *
 * Storage is caller-owned like sat_mesh_t: the asset points at const
 * generated arrays, and upload/draw helpers write into caller-supplied
 * sat_vdp1_texture_t[] / sat_mesh_t storage. The library never allocates.
 */

typedef struct sat_model_texture_asset {
    const uint8_t* pixels; /* indexed8, pixel_count == width*height bytes */
    uint16_t width;        /* VDP1-legal: multiple of 8, 8..504 */
    uint16_t height;       /* VDP1-legal: 1..255 */
    uint16_t palette_slot; /* index into the asset palette list (usually 0) */
    uint16_t flags;        /* SAT_SPRITE_FLAG_OPAQUE when fully opaque */
    uint32_t pixel_count;  /* width * height, for size metadata */
} sat_model_texture_asset_t;

typedef struct sat_model_asset {
    const sat_vec3_t* vertices;
    uint16_t vertex_count;
    const uint16_t* indices; /* 4 vertex indices per face, A/B/C/D order */
    uint16_t face_count;
    /* face_count entries, SAT_MESH_TEXTURE_NONE for untextured faces. */
    const uint16_t* face_texture_indices;
    const sat_model_texture_asset_t* textures;
    uint16_t texture_count;
    /* palette_count palettes of 256 RGB555 entries each, shared by all
     * baked textures (first implementation: exactly one). */
    const uint16_t* palettes_rgb555;
    uint16_t palette_count;
    /* VDP1 color-bank base the palettes are uploaded to. Palette slot i
     * goes to bank (palette_base + i). */
    uint16_t palette_base;
    uint16_t reserved;
    /* Optional baked-lighting shade palette: shade_palette_count RGB555
     * entries (at most 256) that sat_model_animation_asset_t::face_shades
     * index. Entry 0 is reserved. Solid-color assets set texture_count to 0,
     * every face_texture_indices entry to SAT_MESH_TEXTURE_NONE, and carry
     * their colors here instead of in textures. Zero for textured assets. */
    const uint16_t* shade_palette_rgb555;
    uint16_t shade_palette_count;
    /* Optional per-face base shade for Gouraud drawing: face_count indices
     * into the shade palette, each face's color at the middle light level.
     * The baked per-vertex corrections (sat_anim_vertex_gouraud) brighten or
     * darken it towards each corner. Null when not baked. */
    const uint8_t* face_base_shades;
} sat_model_asset_t;

/* Validates a compiled-model descriptor without touching hardware.
 * Checks counts, nulls, VDP1 texture legality, face vertex bounds,
 * face->texture mapping, palette bounds, and pixel_count consistency. */
sat_result_t sat_model_validate(const sat_model_asset_t* asset);

/* Copies generated geometry into caller-owned mesh storage. The mesh must
 * already be bound with sat_mesh_init and large enough; returns
 * SAT_ERR_CAPACITY when vertex_cap/face_cap is too small. This is an
 * explicit copy rather than a const-cast: sat_mesh_t vertices are mutable
 * by contract, generated arrays are const. */
sat_result_t sat_model_copy_to_mesh(const sat_model_asset_t* asset, sat_mesh_t* mesh);

/* Uploads the asset palette(s) once and each unique baked texture once.
 * out_textures must hold at least texture_count entries. Uses the split
 * palette/texture upload path so N faces sharing one palette cost one
 * CRAM write. Returns SAT_ERR_CAPACITY when out_cap < texture_count or
 * VDP1 VRAM is exhausted. */
sat_result_t sat_model_upload_textures(
    const sat_model_asset_t* asset,
    sat_vdp1_texture_t* out_textures,
    uint16_t out_cap
);

/* Binds an uploaded model for drawing: fills a sat_mesh_draw_t that draws
 * the mesh with the model's textures. face_colors may be null. The caller
 * owns order/depth scratch (face_count entries each) when SORT is set.
 *
 * Meshes past 255 faces sort through `order16` (see sat_mesh_draw_t); use
 * sat_model_bind_draw_ex to provide it. The legacy entry keeps order16
 * null and still serves every mesh up to 255 faces unchanged. */
sat_result_t sat_model_bind_draw(
    const sat_model_asset_t* asset,
    const sat_mesh_t* mesh,
    const sat_vdp1_texture_t* textures,
    uint16_t texture_count,
    const sat_mat4_t* view_proj,
    const sat_vec3_t* eye,
    uint16_t color,
    const uint16_t* face_colors,
    sat_fx16_t ambient,
    uint16_t flags,
    uint8_t* order,
    uint32_t* depth,
    sat_mesh_draw_t* out_draw
);

sat_result_t sat_model_bind_draw_ex(
    const sat_model_asset_t* asset,
    const sat_mesh_t* mesh,
    const sat_vdp1_texture_t* textures,
    uint16_t texture_count,
    const sat_mat4_t* view_proj,
    const sat_vec3_t* eye,
    uint16_t color,
    const uint16_t* face_colors,
    sat_fx16_t ambient,
    uint16_t flags,
    uint8_t* order,
    uint16_t* order16,
    uint32_t* depth,
    sat_mesh_draw_t* out_draw
);

/* Fills out_colors[face] with every face's Gouraud base color (see
 * face_base_shades). Static, so once at load is enough. Returns
 * SAT_ERR_UNSUPPORTED when the asset has none and SAT_ERR_CAPACITY when
 * color_cap is below face_count. */
sat_result_t sat_model_face_base_colors(
    const sat_model_asset_t* asset,
    uint16_t* out_colors,
    uint16_t color_cap
);

/* Geometry bounds in fixed point, derived from the generic descriptor so
 * examples center the model without per-asset magic coordinates. */
sat_result_t sat_model_compute_bounds(
    const sat_model_asset_t* asset,
    sat_vec3_t* out_min,
    sat_vec3_t* out_max
);

sat_result_t sat_model_compute_center(
    const sat_model_asset_t* asset,
    sat_vec3_t* out_center
);

/* Total indexed texture payload bytes (sum of width*height). */
uint32_t sat_model_texture_bytes(const sat_model_asset_t* asset);

/* Estimated VDP1 VRAM bytes for the texture payload with the HAL's 8-byte
 * cursor alignment applied per texture. */
uint32_t sat_model_vram_estimate_bytes(const sat_model_asset_t* asset);

#ifdef __cplusplus
}
#endif

#endif /* SATURN_MODEL3D_H */
