#ifndef SATURN_SATURN_H
#define SATURN_SATURN_H

/* Backward-compatible umbrella header.
 * New code should prefer narrow subsystem headers. */

#include "saturn/core.h"
#include "saturn/geometry2d.h"
#include "saturn/color.h"
#include "saturn/memory.h"
#include "saturn/ram_cart.h"
#include "saturn/save.h"
#include "saturn/time.h"
#include "saturn/surface.h"
#include "saturn/texture.h"
#include "saturn/render2d.h"
#include "saturn/math3d.h"
#include "saturn/mesh3d.h"
#include "saturn/model3d.h"
#include "saturn/anim3d.h"
#include "saturn/render3d.h"
#include "saturn/fade3d.h"
#include "saturn/voxel_terrain.h"
#include "saturn/video.h"
#include "saturn/input.h"
#include "saturn/app.h"
#include "saturn/audio.h"
#include "saturn/cd.h"
#include "saturn/cdfs.h"
#include "saturn/file.h"
#include "saturn/asset.h"
#include "saturn/cd_block.h"
#include "saturn/scene3d.h"
#include "saturn/fmt.h"
#include "saturn/font.h"
#include "saturn/grid.h"
#include "saturn/collide2d.h"
#include "saturn/spatial.h"
#include "saturn/physics.h"
#include "saturn/collide3d.h"
#include "saturn/spatial3.h"
#include "saturn/vdp1.h"
#include "saturn/vdp1_color_calc.h"
#include "saturn/vdp2.h"
#include "saturn/vdp2_rbg0_ground.h"
#include "saturn/vdp2_color_calc.h"

#endif /* SATURN_SATURN_H */
