#ifndef SATURN_SCSP_DSP_H
#define SATURN_SCSP_DSP_H

#include <stdint.h>

#include "saturn/audio.h"
#include "saturn/core.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SCSP DSP effects: an echo and a four-comb reverb.
 *
 * Voices send their output to the DSP (slot send level 0-7, 0 = off), the DSP
 * program keeps a delay line in a ring buffer in Sound RAM and returns the wet
 * signal through EFREG 0, which is mixed into the output by slot 0's effect
 * level and pan (the return). The programs are generated by tools/scsp_dsp.py
 * and simulated there with the Ymir DSP semantics; here only the data (gains,
 * delay) is set.
 *
 * The ring buffer is taken from the resident sound RAM pool (8 KiB aligned, 16
 * KiB to 128 KiB), so it counts in sat_audio_get_stats. One effect runs at a
 * time; starting another replaces it. Gains are 16.16 in [0, 1); 1.0 becomes
 * 4095/4096. */

typedef enum sat_effect_kind {
    SAT_EFFECT_NONE = 0,
    SAT_EFFECT_ECHO = 1,
    SAT_EFFECT_REVERB = 2
} sat_effect_kind_t;

typedef struct sat_effect_echo_params {
    uint32_t delay_ms;      /* 1..1000 */
    sat_fx16_t feedback;    /* fraction of the echo fed back: the tail decays by this per repeat */
    sat_fx16_t wet;         /* level of the echo at the output of the DSP */
    sat_fx16_t input_gain;  /* level of the voices entering the delay line */
} sat_effect_echo_params_t;

typedef struct sat_effect_reverb_params {
    sat_fx16_t feedback;    /* decay of each comb; near 1.0 rings for a long time */
    sat_fx16_t wet;
    sat_fx16_t input_gain;
} sat_effect_reverb_params_t;

typedef struct sat_effect_info {
    uint8_t kind;           /* sat_effect_kind_t */
    uint8_t ring_length;    /* RBL code 0-3: 8K, 16K, 32K, 64K words */
    uint8_t default_send;
    uint8_t return_level;
    uint32_t ring_offset;   /* Sound RAM byte offset of the ring buffer */
    uint32_t ring_bytes;
    uint32_t delay_samples; /* echo delay, or the shortest reverb comb */
} sat_effect_info_t;

sat_result_t sat_effect_echo_start(const sat_effect_echo_params_t* params);
sat_result_t sat_effect_reverb_start(const sat_effect_reverb_params_t* params);
/* Stops the DSP, silences the return and frees the ring buffer. */
sat_result_t sat_effect_stop(void);
/* Changes the gains of the running effect without restarting it. */
sat_result_t sat_effect_set_gains(sat_fx16_t feedback, sat_fx16_t wet, sat_fx16_t input_gain);

/* Send level of voices started after this call (0 = dry only, 7 = full). Voices
 * already playing keep theirs; change one with sat_voice_set_effect_send. */
sat_result_t sat_effect_set_default_send(uint8_t level);
sat_result_t sat_voice_set_effect_send(sat_voice_t voice, uint8_t level);
/* Level (0-7) and pan (SAT_AUDIO_PAN_LEFT..RIGHT) of the effect output. */
sat_result_t sat_effect_set_return(uint8_t level, int16_t pan);
sat_result_t sat_effect_info(sat_effect_info_t* out_info);
/* Copies `count` samples of the running effect's delay line, starting at word
 * `first_word` of the ring (the ring is sat_effect_info().ring_bytes / 2 words).
 * The DSP keeps writing while this runs, so a copy is a diagnostic snapshot. */
sat_result_t sat_effect_read_ring(uint32_t first_word, int16_t* out, uint32_t count);

#ifdef __cplusplus
}
#endif

#endif
