# vdp2_nbg0_image - VDP2 NBG0 tiled image demo
EXAMPLE_INPUT        := examples/vdp2_nbg0_image/assets/floor.tga
EXAMPLE_RESIZE       := 64 64
EXAMPLE_ASSET_PREFIX := $(GENERATED_DIR)/vdp2_nbg0_image/bg
EXAMPLE_ASSETS       := $(EXAMPLE_ASSET_PREFIX).c
EXAMPLE_HEADERS      := $(EXAMPLE_ASSET_PREFIX).h
