/* Generated by tools/scu_dsp.py; do not edit. */
#include <stdint.h>

enum { kDspTransformProgramAddress = 0, kDspTransformProgramCount = 30 };
static const uint32_t kDspTransformProgram[kDspTransformProgramCount] = {
    0x00001C00u, 0x00001D00u, 0x00001E00u, 0x00001F3Fu,
    0x00003A03u, 0x00001B06u, 0x00001F00u, 0x00003305u,
    0x00003305u, 0x00003305u, 0x00001F00u, 0x00001C00u,
    0x0249C000u, 0x034BC000u, 0x1B4DC000u, 0x19041F00u,
    0x18043209u, 0x0249C000u, 0x034BC000u, 0x1B4DC000u,
    0x19041F00u, 0x18043209u, 0x0249C000u, 0x034BC000u,
    0x1B4DC000u, 0x19040000u, 0x18043209u, 0xE0000000u,
    0x00000000u, 0xF8000000u,
};
