# vdp2_rbg0_infinite_plane - RBG0 rotation plane with perspective
EXAMPLE_INPUT        := examples/$(EXAMPLE)/assets/seamless_sea.png
EXAMPLE_RESIZE       := 256 256
EXAMPLE_ASSET_PREFIX := $(GENERATED_DIR)/vdp2_rbg0_infinite_plane/seamless_sea
EXAMPLE_ASSETS       := $(EXAMPLE_ASSET_PREFIX).c
EXAMPLE_HEADERS      := $(EXAMPLE_ASSET_PREFIX).h
