#!/usr/bin/env python3
import sys
import argparse

def bin2c(input_file, output_file, array_name):
    with open(input_file, 'rb') as f:
        data = f.read()
    
    with open(output_file, 'w') as f:
        f.write(f"// Generated by bin2c\n")
        f.write(f"#include <stdint.h>\n\n")
        f.write(f"const uint8_t {array_name}[] = {{\n")
        
        for i, byte in enumerate(data):
            if i % 12 == 0:
                f.write("    ")
            f.write(f"0x{byte:02x}, ")
            if (i + 1) % 12 == 0:
                f.write("\n")
        
        f.write("\n};\n")
        f.write(f"const size_t {array_name}_len = sizeof({array_name});\n")
    
    print(f"Converted {len(data)} bytes from {input_file} to {output_file}")

def main():
    parser = argparse.ArgumentParser(description='Convert binary files to C arrays')
    parser.add_argument('input', help='Input binary file')
    parser.add_argument('output', help='Output C file')
    parser.add_argument('--name', default='data', help='Array name (default: data)')
    args = parser.parse_args()
    
    bin2c(args.input, args.output, args.name)

if __name__ == '__main__':
    main()
