# text_sprite - Sonic head texture
EXAMPLE_INPUT        := examples/$(EXAMPLE)/assets/sonic_head.png
EXAMPLE_RESIZE       := 128 96
EXAMPLE_ASSET_PREFIX := $(GENERATED_DIR)/text_sprite/sonic_head
EXAMPLE_ASSETS       := $(EXAMPLE_ASSET_PREFIX).c
EXAMPLE_HEADERS      := $(EXAMPLE_ASSET_PREFIX).h
