"""C source emission: the only module that knows about the runtime's
table shapes (examples/common/ikemen_anim.h). Everything upstream
depends on abstractions; this module adapts them to C arrays."""
from __future__ import annotations

from dataclasses import dataclass

from .stage import ComposedStage

INDENT = "    "


@dataclass
class FrameAsset:
    """One AIR frame resolved against the SFF sprite bank."""
    action: int
    index: int
    width: int
    height: int
    ax: int
    ay: int
    ticks: int
    flip_h: bool
    flip_v: bool
    sprite_key: tuple[int, int]     # unique pixel blob key
    pixel_offset: int = 0           # filled during emission
    clsn2: list = None


def _c_bytes(data) -> str:
    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append(INDENT + ",".join(str(b) for b in chunk) + ",")
    return "\n".join(lines)


def _c_words(words) -> str:
    lines = []
    for i in range(0, len(words), 8):
        chunk = words[i:i + 8]
        lines.append(INDENT + ",".join(f"0x{w:04X}u" for w in chunk) + ",")
    return "\n".join(lines)


def emit_frames(prefix: str, symbol: str, frames: list[FrameAsset],
                sprite_pixels: dict[tuple[int, int], bytes],
                palettes: dict[str, list[int]], source_name: str) -> tuple[str, str]:
    """Returns (c_source, header_source) for a char frame table set."""
    blob = bytearray()
    sprite_offsets: dict[tuple[int, int], int] = {}
    for frame in frames:
        if frame.sprite_key not in sprite_pixels:
            raise KeyError(f"missing pixels for sprite {frame.sprite_key}")
        if frame.sprite_key not in sprite_offsets:
            sprite_offsets[frame.sprite_key] = len(blob)
            blob += sprite_pixels[frame.sprite_key]
        frame.pixel_offset = sprite_offsets[frame.sprite_key]

    symbol = _sanitize(symbol)
    frames_init = "\n".join(
        f"{INDENT}{{{f.action}u, {f.index}u, {f.width}u, {f.height}u, "
        f"{f.ax}, {f.ay}, {max(f.ticks, 0)}u, "
        f"{(1 if f.flip_h else 0) | (2 if f.flip_v else 0)}u, "
        f"{f.pixel_offset}u}},"
        for f in frames)
    blob_c = _c_bytes(blob)
    pal_blocks = "\n\n".join(
        f"const uint16_t {symbol}_palette_{name}[256] = {{\n{_c_words(words)}\n}};"
        for name, words in palettes.items())

    c = (f"/* Auto-generated by tools/ikemen_sff from {source_name}. */\n"
         f"#include <stdint.h>\n"
         f"#include \"{symbol}_frames.h\"\n\n"
         f"const uint8_t {symbol}_pixels[{len(blob)}] = {{\n{blob_c}\n}};\n\n"
         f"const ik_frame_t {symbol}_frames[{len(frames)}] = {{\n{frames_init}\n}};\n\n"
         f"const uint16_t {symbol}_frame_count = {len(frames)}u;\n\n"
         f"{pal_blocks}\n")
    h = (f"/* Auto-generated by tools/ikemen_sff from {source_name}. */\n"
         f"#pragma once\n#include <stdint.h>\n"
         f"#include \"examples/common/ikemen_anim.h\"\n\n"
         f"#define {symbol.upper()}_FRAME_COUNT {len(frames)}\n"
         f"#define {symbol.upper()}_PIXELS_BYTES {len(blob)}\n\n"
         f"extern const uint8_t {symbol}_pixels[];\n"
         f"extern const ik_frame_t {symbol}_frames[];\n"
         f"extern const uint16_t {symbol}_frame_count;\n"
         + "".join(f"extern const uint16_t {symbol}_palette_{name}[256];\n"
                   for name in palettes) + "\n")
    return c, h


def emit_stage(prefix: str, symbol: str, stage: ComposedStage,
               source_name: str) -> tuple[str, str]:
    """Returns (c_source, header_source) for a VDP2 stage plane."""
    symbol = _sanitize(symbol)
    pixels_c = _c_bytes(stage.pixels)
    pal_c = _c_words(stage.palette)
    c = (f"/* Auto-generated by tools/ikemen_sff from {source_name}. */\n"
         f"#include <stdint.h>\n"
         f"#include \"{symbol}_plane.h\"\n\n"
         f"const uint8_t {symbol}_pixels[{stage.width * stage.height}] = {{\n{pixels_c}\n}};\n\n"
         f"const uint16_t {symbol}_palette[256] = {{\n{pal_c}\n}};\n\n"
         f"const uint16_t {symbol}_width = {stage.width}u;\n"
         f"const uint16_t {symbol}_height = {stage.height}u;\n")
    h = (f"/* Auto-generated by tools/ikemen_sff from {source_name}. */\n"
         f"#pragma once\n#include <stdint.h>\n\n"
         f"extern const uint8_t {symbol}_pixels[];\n"
         f"extern const uint16_t {symbol}_palette[256];\n"
         f"extern const uint16_t {symbol}_width;\n"
         f"extern const uint16_t {symbol}_height;\n")
    return c, h


def _sanitize(symbol: str) -> str:
    return "".join(c if c.isalnum() or c == "_" else "_" for c in symbol)
