/* Generated by tools/stage2d_tool.py from a stage2d spec. Do not edit. */
#ifndef SYNTH_H
#define SYNTH_H

#include <stdint.h>

#include "saturn/terrain2.h"
#include "saturn/entity_stream2.h"
#include "saturn/sprite_clip.h"
#include "saturn/path2.h"

#ifdef __cplusplus
extern "C" {
#endif

#define SYNTH_PROFILE_COUNT 8u
#define SYNTH_PROFILE_EMPTY 0u
#define SYNTH_PROFILE_BLOCK 1u
#define SYNTH_PROFILE_HALF 2u
#define SYNTH_PROFILE_HALF_FLIP_Y 3u
#define SYNTH_PROFILE_RAMP 4u
#define SYNTH_PROFILE_RAMP_FLIP_X 5u
#define SYNTH_PROFILE_RAMP_ROT90 6u
#define SYNTH_PROFILE_PLAT 7u
extern const sat_terrain_profile2_t synth_profiles[SYNTH_PROFILE_COUNT];

/* Terrain: bind with sat_terrain_map2_init(&map, synth_profiles, SYNTH_PROFILE_COUNT, synth_terrain_metatiles,
 * SYNTH_TERRAIN_METATILE_COUNT, SYNTH_TERRAIN_METATILE_SHIFT, SYNTH_TERRAIN_COLS, SYNTH_TERRAIN_ROWS),
 * then sat_terrain_map2_add_layer for each synth_terrain_layer_N and sat_terrain_map2_set_outside(SYNTH_TERRAIN_OUTSIDE). */
#define SYNTH_TERRAIN_METATILE_SHIFT 1u
#define SYNTH_TERRAIN_METATILE_COUNT 6u
#define SYNTH_TERRAIN_COLS 4u
#define SYNTH_TERRAIN_ROWS 2u
#define SYNTH_TERRAIN_LAYER_COUNT 2u
#define SYNTH_TERRAIN_OUTSIDE SAT_TERRAIN2_OUTSIDE_SOLID
extern const uint16_t synth_terrain_metatiles[SYNTH_TERRAIN_METATILE_COUNT * 4u];
extern const uint16_t synth_terrain_layer_0[SYNTH_TERRAIN_COLS * SYNTH_TERRAIN_ROWS];
extern const uint16_t synth_terrain_layer_1[SYNTH_TERRAIN_COLS * SYNTH_TERRAIN_ROWS];

/* Stage map: the shared metatile table and one map of metatile indices per layer. */
#define SYNTH_MAP_SHIFT 1u
#define SYNTH_MAP_METATILE_COUNT 7u
#define SYNTH_MAP_LAYER_COUNT 2u
extern const uint16_t synth_map_tileset[SYNTH_MAP_METATILE_COUNT * 4u];
#define SYNTH_MAP_LAYER_0_W 3u
#define SYNTH_MAP_LAYER_0_H 2u
extern const uint16_t synth_map_layer_0[SYNTH_MAP_LAYER_0_W * SYNTH_MAP_LAYER_0_H];
#define SYNTH_MAP_LAYER_1_W 3u
#define SYNTH_MAP_LAYER_1_H 2u
extern const uint16_t synth_map_layer_1[SYNTH_MAP_LAYER_1_W * SYNTH_MAP_LAYER_1_H];

/* Entities: descriptors sorted by region; synth_entity_index is ready for sat_entity_stream2_init. */
#define SYNTH_ENTITY_COUNT 8u
#define SYNTH_ENTITY_REGION_COUNT 15u
extern const sat_entity_desc2_t synth_entity_descs[SYNTH_ENTITY_COUNT];
extern const uint16_t synth_entity_region_start[SYNTH_ENTITY_REGION_COUNT + 1u];
extern const sat_entity_index2_t synth_entity_index;

/* Clips: synth_clip_set is ready for sat_clip_player_init. */
#define SYNTH_CLIP_COUNT 4u
#define SYNTH_CLIP_REGION_COUNT 10u
#define SYNTH_CLIP_IDLE 0u
#define SYNTH_CLIP_RUN 1u
#define SYNTH_CLIP_JUMP 2u
#define SYNTH_CLIP_ROLL 3u
extern const sat_clip_set_t synth_clip_set;

/* Paths: control points (16.16) and the arc-length table for sat_path2_attach_table. */
#define SYNTH_PATH_ARC_POINT_COUNT 4u
#define SYNTH_PATH_ARC_TABLE_ENTRIES 65u
extern const sat_vec2_t synth_path_arc_points[SYNTH_PATH_ARC_POINT_COUNT];
extern const sat_fx16_t synth_path_arc_table[SYNTH_PATH_ARC_TABLE_ENTRIES];
#define SYNTH_PATH_DIP_POINT_COUNT 3u
#define SYNTH_PATH_DIP_TABLE_ENTRIES 33u
extern const sat_vec2_t synth_path_dip_points[SYNTH_PATH_DIP_POINT_COUNT];
extern const sat_fx16_t synth_path_dip_table[SYNTH_PATH_DIP_TABLE_ENTRIES];

#ifdef __cplusplus
}
#endif

#endif /* SYNTH_H */
