/* Generated by tools/stage2d_tool.py from a stage2d spec. Do not edit. */
#include "synth.h"

const sat_terrain_profile2_t synth_profiles[SYNTH_PROFILE_COUNT] = {
    /* 0 empty */ {{0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0}, 0, 0, 0, 0, 0},
    /* 1 block */ {{8, 8, 8, 8, 8, 8, 8, 8}, {-8, -8, -8, -8, -8, -8, -8, -8}, 1, 0, 0, 1, 0},
    /* 2 half */ {{4, 4, 4, 4, 4, 4, 4, 4}, {0, 0, 0, 0, -8, -8, -8, -8}, 2, 0, 0, 1, 0},
    /* 3 half.flip_y */ {{-4, -4, -4, -4, -4, -4, -4, -4}, {-8, -8, -8, -8, 0, 0, 0, 0}, 2, 128, 0, 1, 0},
    /* 4 ramp */ {{1, 2, 3, 4, 5, 6, 7, 8}, {1, 2, 3, 4, 5, 6, 7, -8}, 3, 224, 0, 1, 0},
    /* 5 ramp.flip_x */ {{8, 7, 6, 5, 4, 3, 2, 1}, {-1, -2, -3, -4, -5, -6, -7, -8}, 3, 32, 0, 1, 0},
    /* 6 ramp.rot90 */ {{8, 7, 6, 5, 4, 3, 2, 1}, {-1, -2, -3, -4, -5, -6, -7, -8}, 3, 32, 0, 1, 0},
    /* 7 plat */ {{2, 2, 2, 2, 2, 2, 2, 2}, {0, 0, 0, 0, 0, 0, -8, -8}, 4, 0, 1, 1, 0},
};

const uint16_t synth_terrain_metatiles[SYNTH_TERRAIN_METATILE_COUNT * 4u] = {
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0001, 0x0001, 0x0004, 0x0000, 0x0001, 0x0001,
    0x0007, 0x0000, 0x0001, 0x0001, 0x0000, 0x0000, 0x0002, 0x0002, 0x0000, 0x0404, 0x0002, 0x0002
};

const uint16_t synth_terrain_layer_0[SYNTH_TERRAIN_COLS * SYNTH_TERRAIN_ROWS] = {
    0x0000, 0x0000, 0x0000, 0x0000, 0x0001, 0x0002, 0x0003, 0x0001
};

const uint16_t synth_terrain_layer_1[SYNTH_TERRAIN_COLS * SYNTH_TERRAIN_ROWS] = {
    0x0000, 0x0000, 0x0000, 0x0000, 0x0004, 0x0005, 0x0004, 0x0004
};

const uint16_t synth_map_tileset[SYNTH_MAP_METATILE_COUNT * 4u] = {
    0x0000, 0x0000, 0x0000, 0x0000, 0x0005, 0x0006, 0x0007, 0x0008, 0x0001, 0x0002, 0x0003, 0x0004,
    0x0009, 0x0009, 0x0009, 0x0009, 0x0009, 0x0000, 0x0009, 0x0000, 0x0009, 0x0009, 0x0000, 0x0000,
    0x0009, 0x0000, 0x0000, 0x0000
};

const uint16_t synth_map_layer_0[SYNTH_MAP_LAYER_0_W * SYNTH_MAP_LAYER_0_H] = {
    0x0000, 0x0001, 0x0000, 0x0002, 0x0002, 0x0002
};

const uint16_t synth_map_layer_1[SYNTH_MAP_LAYER_1_W * SYNTH_MAP_LAYER_1_H] = {
    0x0003, 0x0003, 0x0004, 0x0005, 0x0005, 0x0006
};

const sat_entity_desc2_t synth_entity_descs[SYNTH_ENTITY_COUNT] = {
    {10, 10, 2, 0},
    {40, 24, 1, 7},
    {41, 25, 1, 8},
    {63, 31, 1, 0},
    {130, 5, 5, 65535},
    {64, 32, 4, 0},
    {12, 70, 2, 1},
    {100, 90, 3, 0},
};

const uint16_t synth_entity_region_start[SYNTH_ENTITY_REGION_COUNT + 1u] = {
    0, 1, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7,
    7, 7, 8, 8
};

const sat_entity_index2_t synth_entity_index = {
    synth_entity_descs, synth_entity_region_start, 0, 0,
    8, 5, 3, 5, 0};

static const sat_clip_shape_t synth_clip_shapes[3] = {
    {-4, -14, 8, 14, 1, 0, 0},
    {4, -8, 6, 4, 2, 1, 0},
    {6, -2, 0, 0, 3, 0, 0},
};

static const sat_clip_frame_t synth_clip_idle_frames[2] = {
    {{0, 0, 16, 16}, 8, 16, 3, 0, 0, 1, 0},
    {{16, 0, 16, 16}, 8, 16, 3, 0, 0, 1, 0},
};

static const sat_clip_frame_t synth_clip_run_frames[3] = {
    {{0, 16, 16, 16}, 8, 16, 2, 10, 0, 0, 0},
    {{16, 16, 16, 16}, 8, 16, 2, 0, 0, 2, 0},
    {{32, 16, 16, 16}, 8, 16, 2, 0, 0, 0, 0},
};

static const sat_clip_frame_t synth_clip_jump_frames[2] = {
    {{0, 32, 16, 16}, 8, 8, 4, 5, 0, 0, 0},
    {{16, 32, 16, 16}, 8, 8, 4, 7, 2, 1, 0},
};

static const sat_clip_frame_t synth_clip_roll_frames[3] = {
    {{0, 32, 16, 16}, 8, 8, 1, 0, 0, 0, 0},
    {{16, 32, 16, 16}, 8, 8, 1, 0, 0, 0, 0},
    {{32, 32, 16, 16}, 8, 8, 1, 0, 0, 0, 0},
};

static const sat_clip_t synth_clips[4] = {
    {synth_clip_idle_frames, 2, 0, SAT_CLIP_LOOP, {0, 0, 0}},
    {synth_clip_run_frames, 3, 1, SAT_CLIP_LOOP, {0, 0, 0}},
    {synth_clip_jump_frames, 2, 0, SAT_CLIP_ONCE, {0, 0, 0}},
    {synth_clip_roll_frames, 3, 0, SAT_CLIP_PING_PONG, {0, 0, 0}},
};

const sat_clip_set_t synth_clip_set = {synth_clips, 4, 3, synth_clip_shapes};

const sat_vec2_t synth_path_arc_points[SYNTH_PATH_ARC_POINT_COUNT] = {
    {0, 0},
    {2621440, 0},
    {2621440, 2621440},
    {5242880, 2621440},
};

const sat_fx16_t synth_path_arc_table[SYNTH_PATH_ARC_TABLE_ENTRIES] = {
    0, 121000, 238400, 352438, 463353, 571379, 676748, 779684,
    880410, 979139, 1076075, 1171414, 1265344, 1358037, 1449657, 1540355,
    1630268, 1719521, 1808227, 1896486, 1984384, 2071998, 2159391, 2246619,
    2333726, 2420747, 2507712, 2594639, 2681546, 2768442, 2855333, 2942222,
    3029112, 3116001, 3202890, 3289781, 3376677, 3463584, 3550512, 3637476,
    3724497, 3811604, 3898832, 3986226, 4073839, 4161737, 4249996, 4338702,
    4427955, 4517868, 4608566, 4700186, 4792879, 4886809, 4982149, 5079085,
    5177813, 5278539, 5381476, 5486844, 5594870, 5705785, 5819823, 5937223,
    6058223
};

const sat_vec2_t synth_path_dip_points[SYNTH_PATH_DIP_POINT_COUNT] = {
    {0, 0},
    {1966080, 3276800},
    {3932160, 0},
};

const sat_fx16_t synth_path_dip_table[SYNTH_PATH_DIP_TABLE_ENTRIES] = {
    0, 233379, 455980, 668027, 869780, 1061543, 1243667, 1416563,
    1580711, 1736672, 1885101, 2026755, 2162507, 2293345, 2420373, 2544798,
    2667900, 2791002, 2915426, 3042455, 3173293, 3309044, 3450698, 3599127,
    3755089, 3919237, 4092132, 4274256, 4466019, 4667773, 4879820, 5102420,
    5335799
};
