# vdp2_infinite_plan - RBG0 infinite plane (scrolling tiled sea texture)
EXAMPLE_INPUT        := examples/$(EXAMPLE)/assets/seamless_sea.png
EXAMPLE_RESIZE       := 256 256
EXAMPLE_ASSET_PREFIX := $(GENERATED_DIR)/vdp2_infinite_plan/seamless_sea
EXAMPLE_ASSETS       := $(EXAMPLE_ASSET_PREFIX).c
EXAMPLE_HEADERS      := $(EXAMPLE_ASSET_PREFIX).h
