#!/usr/bin/env python3
"""Assembles the resident 68000 sound driver (src/hal/scsp/sound_driver.m68k) and
writes src/hal/scsp/sound_driver_image.h, the bytes the SH-2 copies into Sound RAM.

Needs a GNU assembler and linker for the 68000: `m68k-elf-*` or the
`m68k-apple-macos-*` binutils that MSYS2 ships (pacman -S
mingw-w64-ucrt-x86_64-m68k-apple-macos-binutils). The image is checked in, so
nobody without the toolchain needs to rebuild it; tests/tools/test_sound_driver.py
compares the header with a fresh build when the tools are present.

    python tools/build_sound_driver.py [--check]
"""

import argparse
import os
import shutil
import subprocess
import sys
import tempfile

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
SOURCE = os.path.join(REPO, "src", "hal", "scsp", "sound_driver.m68k")
HEADER = os.path.join(REPO, "src", "hal", "scsp", "sound_driver_image.h")
PREFIXES = ("m68k-elf-", "m68k-apple-macos-", "m68k-linux-gnu-")


def find_tools():
    for prefix in PREFIXES:
        tools = {name: shutil.which(prefix + name) for name in ("as", "ld", "objcopy")}
        if all(tools.values()):
            return tools
    extra = os.environ.get("M68K_BIN") or ("C:/msys64/ucrt64/bin" if os.path.isdir("C:/msys64/ucrt64/bin") else None)
    if extra:
        for prefix in PREFIXES:
            tools = {name: shutil.which(prefix + name, path=extra) for name in ("as", "ld", "objcopy")}
            if all(tools.values()):
                return tools
    return None


def assemble_image(tools):
    with tempfile.TemporaryDirectory() as work:
        obj = os.path.join(work, "sd.o")
        elf = os.path.join(work, "sd.elf")
        raw = os.path.join(work, "sd.bin")
        for command in ([tools["as"], "-m68000", "-o", obj, SOURCE],
                        [tools["ld"], "-Ttext=0", "-o", elf, obj],
                        [tools["objcopy"], "-O", "binary", elf, raw]):
            result = subprocess.run(command, capture_output=True, text=True)
            if result.returncode != 0:
                raise RuntimeError("%s failed:\n%s%s" % (command[0], result.stdout, result.stderr))
        with open(raw, "rb") as stream:
            data = stream.read()
    if len(data) % 2:
        data += b"\0"
    return data


def render(data):
    words = [(data[i] << 8) | data[i + 1] for i in range(0, len(data), 2)]
    lines = ["/* Generated by tools/build_sound_driver.py from sound_driver.m68k; do not edit. */",
             "#include <stdint.h>", "",
             "enum { kSoundDriverImageWords = %d };" % len(words),
             "static const uint16_t kSoundDriverImage[kSoundDriverImageWords] = {"]
    for i in range(0, len(words), 8):
        lines.append("    " + ", ".join("0x%04Xu" % w for w in words[i:i + 8]) + ",")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="fail if the checked-in header is stale")
    args = parser.parse_args(argv)
    tools = find_tools()
    if tools is None:
        print("no 68000 assembler found (m68k-elf-* or m68k-apple-macos-*)", file=sys.stderr)
        return 2
    text = render(assemble_image(tools))
    if args.check:
        with open(HEADER, "r", encoding="utf-8", newline="") as stream:
            current = stream.read().replace("\r\n", "\n")
        if current != text:
            print("%s is stale" % HEADER, file=sys.stderr)
            return 1
        return 0
    with open(HEADER, "w", encoding="utf-8", newline="\n") as stream:
        stream.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
