#!/usr/bin/env python3
"""Ikemen stage subset -> LibSaturn VDP2 tables.

Reads a stage DEF (+ optional AIR) and emits VDP2-friendly layer params:
far parallax factors, tile sizes, scroll speeds. Drops bgVideo / Model-GLTF /
zoomscaledelta (documented as unsupported in v1).

Usage:
  python tools/ikemen_stage_to_saturn.py --def stages/kfm/kfm.def \
      --out-prefix build/generated/ikemen_saturn/stage_kfm --symbol stage_kfm
"""
from __future__ import annotations
import argparse
import configparser
import json
from pathlib import Path


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--def", dest="def_path", required=True)
    ap.add_argument("--out-prefix", required=True)
    ap.add_argument("--symbol", required=True)
    args = ap.parse_args()

    def_path = Path(args.def_path)
    cfg = configparser.ConfigParser(strict=False, interpolation=None)
    cfg.optionxform = str
    cfg.read(def_path, encoding="utf-8", errors="ignore")

    layers: list[dict] = []
    dropped: list[str] = []
    for sec in cfg.sections():
        low = sec.lower()
        if low.startswith("bg "):
            d = dict(cfg.items(sec))
            btype = str(d.get("type", "normal")).lower()
            if btype in ("anim", "normal", "parallax"):
                try:
                    layers.append({
                        "name": sec[3:].strip(),
                        "type": btype,
                        "xscale": float(str(d.get("xscale", "1")).split(",")[0]),
                        "yscal": 1.0,
                        "tile_x": int(float(str(d.get("tilex", "0")).split(",")[0] or 0)),
                        "velocity": float(str(d.get("velocity", "0")).split(",")[0]),
                    })
                except ValueError:
                    layers.append({"name": sec[3:].strip(), "type": btype})
            elif btype in ("video", "model", "3d"):
                dropped.append(sec)
    # Keep VDP2 budget: max 4 scroll layers.
    layers = layers[:4]

    out_prefix = Path(args.out_prefix)
    out_prefix.parent.mkdir(parents=True, exist_ok=True)
    sym = "".join(c if (c.isalnum() or c == "_") else "_" for c in args.symbol)
    c_text = (f"/* Auto-generated by ikemen_stage_to_saturn.py from {def_path.name} */\n"
              f"#include <stdint.h>\nconst int32_t {sym}_layer_count = {len(layers)};\n")
    h_text = f"#pragma once\n#include <stdint.h>\nextern const int32_t {sym}_layer_count;\n"
    (out_prefix.parent / (out_prefix.name + ".c")).write_text(c_text, encoding="utf-8")
    (out_prefix.parent / (out_prefix.name + ".h")).write_text(h_text, encoding="utf-8")
    (out_prefix.parent / (out_prefix.name + ".ikemen_stage.json")).write_text(
        json.dumps({"symbol": sym, "layers": layers, "dropped": dropped}, indent=2),
        encoding="utf-8")
    if dropped:
        print(f"[ikemen-stage] dropped unsupported BGs: {dropped}")
    print(f"[ikemen-stage] wrote {out_prefix.name}.c/.h layers={len(layers)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
