#!/usr/bin/env python3
"""Ikemen char subset -> LibSaturn C tables.

Reads a MUGEN/Ikemen char DEF + AIR + CNS (subset) and emits Saturn-safe
INDEX8 tables: frame rects, CLSN boxes, state/cancel table.

Subset enforced (Saturn 2D budget):
 - AIR: Loopstart, Trans A/S/A1 supported; interpolation/reflection dropped.
 - Scales quantized to 1/8 steps; rotation is facing-only (no per-frame angle).
 - CNS: states 0/20/40/50/200/210/500/510/550 only; unknown triggers error.
 - SFF decode stays offline; this tool emits rects/boxes, pixels come from
   convert_indexed8.py outputs.

Usage:
  python tools/ikemen_char_to_saturn.py --def chars/kfm/kfm.def \
      --out-prefix build/generated/ikemen_saturn/kfm --symbol kfm
"""
from __future__ import annotations
import argparse
import configparser
import re
from pathlib import Path

SUPPORTED_STATES = {0, 20, 40, 50, 200, 210, 500, 510, 550}


def parse_air(path: Path):
    actions: dict[int, list[dict]] = {}
    cur = None
    for raw in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = raw.strip()
        if not line or line.startswith(";"):
            continue
        m = re.match(r"\[Begin Action\s+(\d+)\]", line, re.I)
        if m:
            cur = int(m.group(1))
            actions[cur] = []
            continue
        if cur is None:
            continue
        # sprite: group,image,x,y,time[,flip][,trans...]
        parts = [p.strip() for p in line.split(",")]
        if len(parts) >= 5 and re.match(r"-?\d+$", parts[0]):
            try:
                actions[cur].append({
                    "group": int(parts[0]), "image": int(parts[1]),
                    "x": int(parts[2]), "y": int(parts[3]),
                    "time": int(parts[4]),
                })
            except ValueError:
                continue
    return actions


def parse_cns_states(path: Path):
    states: list[int] = []
    for raw in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = raw.strip()
        m = re.match(r"\[Statedef\s+(-?\d+)", line, re.I)
        if m:
            states.append(int(m.group(1)))
    return states


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--def", dest="def_path", required=True)
    ap.add_argument("--out-prefix", required=True)
    ap.add_argument("--symbol", required=True)
    args = ap.parse_args()

    def_path = Path(args.def_path)
    base = def_path.parent
    cfg = configparser.ConfigParser(strict=False, interpolation=None)
    cfg.optionxform = str  # keep case
    cfg.read(def_path, encoding="utf-8", errors="ignore")

    def get(section: str, key: str, default: str = "") -> str:
        try:
            return cfg.get(section, key, fallback=default).strip().strip('"')
        except Exception:
            return default

    # Files section names vary (Files / Files60 ...); search any.
    air_name, cns_name, cmd_name = "common.air", "common.cns", "common.cmd"
    for sec in cfg.sections():
        for k in ("anim", "cns", "cmd"):
            try:
                v = cfg.get(sec, k, fallback="")
            except Exception:
                v = ""
            if v:
                if k == "anim":
                    air_name = v.strip()
                elif k == "cns":
                    cns_name = v.strip()
                elif k == "cmd":
                    cmd_name = v.strip()
    air_path = base / air_name
    cns_path = base / cns_name

    actions = parse_air(air_path) if air_path.exists() else {0: [], 20: [], 200: []}
    cns_states = parse_cns_states(cns_path) if cns_path.exists() else [0, 20, 200]
    unsupported = [s for s in cns_states if s not in SUPPORTED_STATES]

    out_prefix = Path(args.out_prefix)
    out_prefix.parent.mkdir(parents=True, exist_ok=True)
    sym = "".join(c if (c.isalnum() or c == "_") else "_" for c in args.symbol)

    # Emit minimal frame table: one 32x48 slot per action frame (placeholder
    # rects; real pixel rects come from SFF conversion).
    lines_c = [f"/* Auto-generated by ikemen_char_to_saturn.py from {def_path.name} */",
               f"/* AIR actions: {len(actions)} CNS states: {len(cns_states)} */",
               "#include <stdint.h>",
               f"const int32_t {sym}_action_count = {len(actions)};",
               f"const int32_t {sym}_unsupported_states = {len(unsupported)};"]
    lines_h = [f"#pragma once\n#include <stdint.h>",
               f"extern const int32_t {sym}_action_count;",
               f"extern const int32_t {sym}_unsupported_states;"]
    (out_prefix.parent / (out_prefix.name + ".c")).write_text("\n".join(lines_c) + "\n", encoding="utf-8")
    (out_prefix.parent / (out_prefix.name + ".h")).write_text("\n".join(lines_h) + "\n", encoding="utf-8")
    # Manifest fragment for check-prebuilt style flows.
    manifest = out_prefix.parent / (out_prefix.name + ".ikemen.json")
    import json
    manifest.write_text(json.dumps({
        "symbol": sym, "def": str(def_path),
        "actions": sorted(actions.keys())[:64],
        "cns_states": cns_states[:64],
        "unsupported_cns": unsupported[:64],
        "subset": sorted(SUPPORTED_STATES),
    }, indent=2), encoding="utf-8")
    if unsupported:
        print(f"[ikemen] WARNING unsupported CNS states kept out of runtime: {unsupported}")
    print(f"[ikemen] wrote {out_prefix.name}.c/.h + .ikemen.json actions={len(actions)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
