"""C emission and size accounting for stage2d data.

The generated arrays are positional initialisers of the runtime structs, so they compile as C and as
C++ and carry no hidden layout. Output is byte-for-byte deterministic for a given spec.
"""

from __future__ import annotations

import re

from .build import StageData
from .entities import index_bytes

BANNER = "/* Generated by tools/stage2d_tool.py from a stage2d spec. Do not edit. */"
MODE_NAMES = {0: "SAT_CLIP_ONCE", 1: "SAT_CLIP_LOOP", 2: "SAT_CLIP_PING_PONG"}
OUTSIDE_NAMES = {0: "SAT_TERRAIN2_OUTSIDE_EMPTY", 1: "SAT_TERRAIN2_OUTSIDE_SOLID", 2: "SAT_TERRAIN2_OUTSIDE_CLAMP"}


def _upper(name: str) -> str:
    return re.sub(r"[^0-9A-Za-z]+", "_", name).strip("_").upper()


def _words(values, columns: int = 12) -> str:
    lines = []
    for i in range(0, len(values), columns):
        lines.append("    " + ", ".join(f"0x{v:04X}" for v in values[i:i + columns]))
    return ",\n".join(lines)


def _ints(values, columns: int = 8) -> str:
    lines = []
    for i in range(0, len(values), columns):
        lines.append("    " + ", ".join(str(v) for v in values[i:i + columns]))
    return ",\n".join(lines)


def _fx(value) -> int:
    return round(value * 65536)


def size_report(stage: StageData) -> dict[str, int]:
    """Bytes of read-only data per section, with the SH-2 struct sizes (4-byte pointers)."""
    out: dict[str, int] = {}
    if stage.profiles:
        out["profiles"] = len(stage.profiles) * 22
    if stage.terrain:
        t = stage.terrain
        out["terrain"] = len(t.tiles.cells) * 2 + len(t.tiles.layers) * t.cols * t.rows * 2
    if stage.stage_map:
        m = stage.stage_map
        out["stage_map"] = len(m.tiles.cells) * 2 + sum(len(layer.cells) for layer in m.tiles.layers) * 2
    if stage.entities:
        e = stage.entities
        out["entities"] = index_bytes(len(e.descs), e.region_cols * e.region_rows)
    if stage.clips:
        c = stage.clips
        out["clips"] = (sum(len(clip.frames) for clip in c.clips) * 20 + len(c.shapes) * 12 + len(c.clips) * 12 + 12)
    if stage.paths:
        out["paths"] = sum(len(p.table) * 4 + len(p.points) * 8 for p in stage.paths)
    return out


def emit_c(stage: StageData) -> tuple[str, str]:
    """Returns (header text, source text)."""
    p = stage.name
    guard = f"{_upper(p)}_H"
    h: list[str] = [BANNER, f"#ifndef {guard}", f"#define {guard}", "", "#include <stdint.h>", ""]
    if stage.profiles:
        h.append('#include "saturn/terrain2.h"')
    if stage.entities:
        h.append('#include "saturn/entity_stream2.h"')
    if stage.clips:
        h.append('#include "saturn/sprite_clip.h"')
    if stage.paths:
        h.append('#include "saturn/path2.h"')
    h += ["", "#ifdef __cplusplus", 'extern "C" {', "#endif", ""]
    c: list[str] = [BANNER, f'#include "{p}.h"', ""]
    P = _upper(p)

    if stage.profiles:
        h.append(f"#define {P}_PROFILE_COUNT {len(stage.profiles)}u")
        for i, prof in enumerate(stage.profiles):
            h.append(f"#define {P}_PROFILE_{_upper(prof.name)} {i}u")
        h.append(f"extern const sat_terrain_profile2_t {p}_profiles[{P}_PROFILE_COUNT];")
        h.append("")
        c.append(f"const sat_terrain_profile2_t {p}_profiles[{P}_PROFILE_COUNT] = {{")
        for i, prof in enumerate(stage.profiles):
            cols = ", ".join(str(v) for v in prof.column)
            rows = ", ".join(str(v) for v in prof.row)
            c.append(f"    /* {i} {prof.name} */ {{{{{cols}}}, {{{rows}}}, {prof.material}, {prof.angle}, {prof.flags}, {prof.category}, 0}},")
        c += ["};", ""]

    if stage.terrain:
        t = stage.terrain
        n = len(t.tiles.layers)
        h += [f"/* Terrain: bind with sat_terrain_map2_init(&map, {p}_profiles, {P}_PROFILE_COUNT, {p}_terrain_metatiles,",
              f" * {P}_TERRAIN_METATILE_COUNT, {P}_TERRAIN_METATILE_SHIFT, {P}_TERRAIN_COLS, {P}_TERRAIN_ROWS),",
              f" * then sat_terrain_map2_add_layer for each {p}_terrain_layer_N and sat_terrain_map2_set_outside({P}_TERRAIN_OUTSIDE). */",
              f"#define {P}_TERRAIN_METATILE_SHIFT {t.shift}u",
              f"#define {P}_TERRAIN_METATILE_COUNT {t.tiles.count}u",
              f"#define {P}_TERRAIN_COLS {t.cols}u",
              f"#define {P}_TERRAIN_ROWS {t.rows}u",
              f"#define {P}_TERRAIN_LAYER_COUNT {n}u",
              f"#define {P}_TERRAIN_OUTSIDE {OUTSIDE_NAMES[t.outside]}",
              f"extern const uint16_t {p}_terrain_metatiles[{P}_TERRAIN_METATILE_COUNT * {1 << (2 * t.shift)}u];"]
        c += [f"const uint16_t {p}_terrain_metatiles[{P}_TERRAIN_METATILE_COUNT * {1 << (2 * t.shift)}u] = {{",
              _words(t.tiles.cells), "};", ""]
        for i, layer in enumerate(t.tiles.layers):
            h.append(f"extern const uint16_t {p}_terrain_layer_{i}[{P}_TERRAIN_COLS * {P}_TERRAIN_ROWS];")
            c += [f"const uint16_t {p}_terrain_layer_{i}[{P}_TERRAIN_COLS * {P}_TERRAIN_ROWS] = {{", _words(layer.cells), "};", ""]
        h.append("")

    if stage.stage_map:
        m = stage.stage_map
        h += [f"/* Stage map: the shared metatile table and one map of metatile indices per layer. */",
              f"#define {P}_MAP_SHIFT {m.shift}u",
              f"#define {P}_MAP_METATILE_COUNT {m.tiles.count}u",
              f"#define {P}_MAP_LAYER_COUNT {len(m.tiles.layers)}u",
              f"extern const uint16_t {p}_map_tileset[{P}_MAP_METATILE_COUNT * {1 << (2 * m.shift)}u];"]
        c += [f"const uint16_t {p}_map_tileset[{P}_MAP_METATILE_COUNT * {1 << (2 * m.shift)}u] = {{", _words(m.tiles.cells), "};", ""]
        for i, layer in enumerate(m.tiles.layers):
            h += [f"#define {P}_MAP_LAYER_{i}_W {layer.cols}u", f"#define {P}_MAP_LAYER_{i}_H {layer.rows}u",
                  f"extern const uint16_t {p}_map_layer_{i}[{P}_MAP_LAYER_{i}_W * {P}_MAP_LAYER_{i}_H];"]
            c += [f"const uint16_t {p}_map_layer_{i}[{P}_MAP_LAYER_{i}_W * {P}_MAP_LAYER_{i}_H] = {{", _words(layer.cells), "};", ""]
        h.append("")

    if stage.entities:
        e = stage.entities
        regions = e.region_cols * e.region_rows
        h += [f"/* Entities: descriptors sorted by region; {p}_entity_index is ready for sat_entity_stream2_init. */",
              f"#define {P}_ENTITY_COUNT {len(e.descs)}u",
              f"#define {P}_ENTITY_REGION_COUNT {regions}u"]
        if e.descs:
            h.append(f"extern const sat_entity_desc2_t {p}_entity_descs[{P}_ENTITY_COUNT];")
        h += [f"extern const uint16_t {p}_entity_region_start[{P}_ENTITY_REGION_COUNT + 1u];",
              f"extern const sat_entity_index2_t {p}_entity_index;", ""]
        if e.descs:
            c.append(f"const sat_entity_desc2_t {p}_entity_descs[{P}_ENTITY_COUNT] = {{")
            for d in e.descs:
                c.append(f"    {{{d.x}, {d.y}, {d.kind}, {d.data}}},")
            c += ["};", ""]
        c += [f"const uint16_t {p}_entity_region_start[{P}_ENTITY_REGION_COUNT + 1u] = {{", _ints(e.region_start, 12), "};", "",
              f"const sat_entity_index2_t {p}_entity_index = {{",
              f"    {p + '_entity_descs' if e.descs else '0'}, {p}_entity_region_start, {e.origin_x}, {e.origin_y},",
              f"    {len(e.descs)}, {e.region_cols}, {e.region_rows}, {e.region_shift}, 0}};", ""]

    if stage.clips:
        cs = stage.clips
        h += [f"/* Clips: {p}_clip_set is ready for sat_clip_player_init. */",
              f"#define {P}_CLIP_COUNT {len(cs.clips)}u",
              f"#define {P}_CLIP_REGION_COUNT {cs.region_count}u"]
        for i, clip in enumerate(cs.clips):
            h.append(f"#define {P}_CLIP_{_upper(clip.name)} {i}u")
        h += [f"extern const sat_clip_set_t {p}_clip_set;", ""]
        if cs.shapes:
            c.append(f"static const sat_clip_shape_t {p}_clip_shapes[{len(cs.shapes)}] = {{")
            for s in cs.shapes:
                c.append(f"    {{{s.x}, {s.y}, {s.w}, {s.h}, {s.kind}, {s.index}, {s.flags}}},")
            c += ["};", ""]
        for clip in cs.clips:
            c.append(f"static const sat_clip_frame_t {p}_clip_{clip.name}_frames[{len(clip.frames)}] = {{")
            for f in clip.frames:
                c.append(f"    {{{{{f.source[0]}, {f.source[1]}, {f.source[2]}, {f.source[3]}}}, {f.pivot[0]}, {f.pivot[1]}, "
                         f"{f.duration}, {f.event}, {f.shape_first}, {f.shape_count}, {f.flags}}},")
            c += ["};", ""]
        c.append(f"static const sat_clip_t {p}_clips[{len(cs.clips)}] = {{")
        for clip in cs.clips:
            c.append(f"    {{{p}_clip_{clip.name}_frames, {len(clip.frames)}, {clip.loop_start}, {MODE_NAMES[clip.mode]}, {{0, 0, 0}}}},")
        c += ["};", "",
              f"const sat_clip_set_t {p}_clip_set = {{{p}_clips, {len(cs.clips)}, {len(cs.shapes)}, "
              f"{p + '_clip_shapes' if cs.shapes else '0'}}};", ""]

    if stage.paths:
        h.append("/* Paths: control points (16.16) and the arc-length table for sat_path2_attach_table. */")
        for path in stage.paths:
            n = len(path.table)
            pn = _upper(path.name)
            h += [f"#define {P}_PATH_{pn}_POINT_COUNT {len(path.points)}u",
                  f"#define {P}_PATH_{pn}_TABLE_ENTRIES {n}u",
                  f"extern const sat_vec2_t {p}_path_{path.name}_points[{P}_PATH_{pn}_POINT_COUNT];",
                  f"extern const sat_fx16_t {p}_path_{path.name}_table[{P}_PATH_{pn}_TABLE_ENTRIES];"]
            c.append(f"const sat_vec2_t {p}_path_{path.name}_points[{P}_PATH_{pn}_POINT_COUNT] = {{")
            for pt in path.points:
                c.append(f"    {{{_fx(pt[0])}, {_fx(pt[1])}}},")
            c += ["};", "", f"const sat_fx16_t {p}_path_{path.name}_table[{P}_PATH_{pn}_TABLE_ENTRIES] = {{", _ints(path.table, 8), "};", ""]
        h.append("")

    h += ["#ifdef __cplusplus", "}", "#endif", "", f"#endif /* {guard} */", ""]
    return "\n".join(h), "\n".join(c).rstrip("\n") + "\n"
