/* Generated by tools/scu_dsp.py; do not edit. */
#include <stdint.h>

enum { kDmaProbeR2W1Address = 0, kDmaProbeR2W1Count = 11 };
static const uint32_t kDmaProbeR2W1[kDmaProbeR2W1Count] = {
    0x00001F00u, 0x00003607u, 0x00003707u, 0x00001D00u,
    0xC0010108u, 0xD3400005u, 0x00000000u, 0x00001D00u,
    0xC0009108u, 0x00000000u, 0xF8000000u,
};
